### PR TITLE
Support looking up instance name with Passenger 5.1

### PR DESCRIPTION
**Pull request by markoudev**
pid file moved from web_server_control_proces.pid to
web_server_info/control_process.pid

### CODE REVIEW

**Comment by foeken** [comment]
I am not the best person to review this, my bash is not good enough :)

**Comment by markoudev** [comment]
Ok! We'll wait for @olafz's thumbs up then :)

**Review by olafz — APPROVED** [review]
I think this nails it!

**Comment by olafz** [comment]
It works! Just deployed it to a server with Passenger 5.1.x:

screen shot 2017-07-29 at 08 01 36

**Pull request merged**
